const express = require('express');
const { WebSocketServer, WebSocket } = require('ws');
const http = require('http');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const { getSystemInfo, restartKiosk, reboot } = require('./lib/system');
const update = require('./lib/update');
const wifi = require('./lib/wifi');
const cdp = require('./lib/cdp');
const hotkey = require('./lib/hotkey');

const SETTINGS_PATH = path.join(__dirname, 'settings.json');

// Default chromium command-line flags for the kiosk. Exposed via /api/kiosk-flags
// so the Advanced settings modal can show/edit them, and chromium-autostart.sh
// reads them from the same endpoint so flag changes propagate without editing
// any shell script.
//   --use-gl / --ignore-gpu-blocklist / --enable-zero-copy / CanvasOopRasterization
//   were removed because they conflict with the Pi chromium wrapper's
//   --use-angle=gles and triggered GPU re-init loops that broke nested
//   overflow:auto scrolling.
//   --window-size is appended dynamically from the saved resolution, not stored
//   here.
// Defaults assume labwc as the compositor (see chromium-autostart.sh), where
// chromium gets a real V3D GL context — so the GPU-accel flags actually take
// effect instead of being dead weight like they were under cage.
// --disable-renderer-accessibility stops chromium auto-enabling the a11y tree
// when it detects the system at-spi bus (heavy CPU on dynamic pages).
const DEFAULT_KIOSK_FLAGS = [
  '--ozone-platform=wayland',
  '--enable-features=UseOzonePlatform,VaapiVideoDecoder',
  '--ignore-gpu-blocklist',
  '--enable-gpu-rasterization',
  '--disable-renderer-accessibility',
  '--kiosk',
  '--start-fullscreen',
  '--noerrdialogs',
  '--disable-infobars',
  '--disable-popup-blocking',
  '--no-sandbox',
  '--remote-debugging-port=9222',
].join('\n');

// Clicker / presentation-remote keystrokes that can break the kiosk and should
// be eaten by the compositor (labwc) BEFORE chromium ever sees them. A web page
// cannot reliably preventDefault these. Observed on the deployed device with
// the actual MK118 remote (the original spec table was guesswork):
//   long-press Tab   -> Alt+Tab  (labwc window-cycle)
//   long-press Enter  -> Alt+F4   (kills chromium window)
//   long-press ArrowUp -> F5      (full page refresh — disruptive in a kiosk)
// labwc keybind syntax (verified against labwc-config.5 / labwc-actions.5 and
// the labwc source): modifier prefixes are S-/C-/A-/W- (A- = Alt); bare keys
// like "F5" are valid.
//
// KEY MECHANISM — read before editing, this is subtle and the first two
// attempts were wrong:
//   labwc forwards a key to the focused app ONLY if it matches NO keybind.
//   If it matches a keybind, labwc ABSORBS it (app never sees it) and runs
//   that bind's action.
//   - `<action name="None"/>` as the sole action means "clear an earlier
//     binding". For A-Tab / A-F4 (which ARE labwc defaults) that REMOVES the
//     default bind → the key then matches nothing → forwarded to Chromium →
//     Alt+F4 still closes Chromium. So `None` is exactly wrong here.
//   - An empty <keybind> is ambiguous across labwc versions.
//   - Correct: bind to a REAL but inert action so the bind MATCHES and the key
//     is absorbed. `Raise` restacks the focused window; with one fullscreen
//     kiosk window it does nothing visible, but it still counts as a match so
//     the key never reaches Chromium. That neutralises both labwc's own
//     default (Alt+Tab/Alt+F4) and non-default keys (F5, which labwc otherwise
//     wouldn't grab at all and would forward to Chromium = page refresh).
//
// Observed on the deployed device with the real MK118 remote (the original
// spec table was guesswork): long-press Tab=Alt+Tab, long-press Enter=Alt+F4,
// long-press ArrowUp=F5.
const NOOP_ACTION = '<action name="Raise"/>';
const SUPPRESSIBLE_KEYS = {
  'alt+f4': { keybind: 'A-F4', label: 'Alt+F4 (long-press Enter — kills Chromium)' },
  'alt+tab': { keybind: 'A-Tab', label: 'Alt+Tab (long-press Tab — switches windows)' },
  'f5': { keybind: 'F5', label: 'F5 (long-press ArrowUp — full page refresh)' },
};
const DEFAULT_SUPPRESS_KEYS = ['alt+f4', 'alt+tab', 'f5'];

// Emit a complete rc.xml (not a fragment) — labwc reads exactly one rc.xml
// from $XDG_CONFIG_HOME/labwc/ and does not merge.
function buildLabwcConfig(suppressKeys) {
  const binds = (Array.isArray(suppressKeys) ? suppressKeys : [])
    .map((k) => SUPPRESSIBLE_KEYS[k])
    .filter(Boolean)
    .map((k) => `    <keybind key="${k.keybind}">${NOOP_ACTION}</keybind>`)
    .join('\n');
  return `<?xml version="1.0"?>
<!-- Generated by OrbitControl /api/labwc-config — do not edit by hand. -->
<labwc_config>
  <keyboard>
${binds || '    <!-- no keys suppressed -->'}
  </keyboard>
</labwc_config>
`;
}

function readSettings() {
  let s = {};
  try {
    s = JSON.parse(fs.readFileSync(SETTINGS_PATH, 'utf8'));
  } catch {}
  return {
    url: s.url || 'https://example.com',
    resolution: s.resolution || { width: 1920, height: 1080 },
    hideCursorDelay: s.hideCursorDelay != null ? s.hideCursorDelay : 10,
    name: s.name || 'Orbit',
    zoom: s.zoom != null ? s.zoom : 1,
    kioskFlags: s.kioskFlags != null ? s.kioskFlags : DEFAULT_KIOSK_FLAGS,
    remoteDebugEnabled: s.remoteDebugEnabled === true,
    suppressKeys: Array.isArray(s.suppressKeys)
      ? s.suppressKeys.filter((k) => SUPPRESSIBLE_KEYS[k])
      : DEFAULT_SUPPRESS_KEYS,
    bookmarks: Array.isArray(s.bookmarks) ? s.bookmarks : [],
  };
}

function writeSettings(settings) {
  fs.writeFileSync(SETTINGS_PATH, JSON.stringify(settings, null, 2));
}

async function toggleAdminPanel() {
  const settings = readSettings();
  const port = parseInt(process.env.PORT, 10) || 80;
  const adminUrl = 'http://localhost' + (port === 80 ? '' : ':' + port) + '/';
  let currentUrl = '';
  try {
    currentUrl = (await cdp.getCurrentUrl()) || '';
  } catch {}
  const isOnAdmin = /^https?:\/\/(localhost|127\.0\.0\.1|0\.0\.0\.0)(:|\/|$)/.test(currentUrl);
  const target = isOnAdmin ? (settings.url || 'https://example.com') : adminUrl;
  await cdp.navigate(target);
  return { target, was: currentUrl };
}

const app = express();
const server = http.createServer(app);
// noServer mode: we handle the HTTP `upgrade` event ourselves so we can route
// /cdp/devtools/* upgrades to the CDP bridge instead of letting WebSocketServer
// swallow every upgrade.
const wss = new WebSocketServer({ noServer: true });
const cdpBridgeWss = new WebSocketServer({ noServer: true });

server.on('upgrade', (req, socket, head) => {
  const url = req.url || '';
  if (url.startsWith('/cdp/devtools/')) {
    if (!readSettings().remoteDebugEnabled) {
      socket.write('HTTP/1.1 403 Forbidden\r\nConnection: close\r\nContent-Length: 0\r\n\r\n');
      socket.destroy();
      return;
    }
    cdpBridgeWss.handleUpgrade(req, socket, head, (clientWs) => {
      bridgeCdpWebSocket(url, clientWs);
    });
    return;
  }
  // Default: control-panel websocket.
  wss.handleUpgrade(req, socket, head, (ws) => {
    wss.emit('connection', ws, req);
  });
});

// --- CDP bridge ----------------------------------------------------------
// Lets a remote debugger (Claude/Puppeteer/chrome://inspect on another machine
// or via the cloudflared tunnel) talk to the kiosk's chromium even though
// chromium itself only listens on 127.0.0.1:9222 (modern chromium ignores
// --remote-debugging-address). We proxy:
//   GET  /cdp/json[/list]    → /json, rewriting webSocketDebuggerUrl + frontendUrl
//   GET  /cdp/json/version   → /json/version, untouched
//   WS   /cdp/devtools/...   → ws://127.0.0.1:9222/devtools/...
// The whole bridge is gated by settings.remoteDebugEnabled — when off, every
// endpoint returns 403, so debugging stays disabled by default.

function rewriteTabsList(tabs, req) {
  const host = req.headers.host || 'localhost';
  const isHttps = req.headers['x-forwarded-proto'] === 'https' || req.protocol === 'https';
  const wsProto = isHttps ? 'wss' : 'ws';
  return tabs.map((t) => {
    const copy = { ...t };
    if (typeof copy.webSocketDebuggerUrl === 'string') {
      copy.webSocketDebuggerUrl = copy.webSocketDebuggerUrl.replace(
        /^ws:\/\/127\.0\.0\.1:9222\/devtools\//,
        `${wsProto}://${host}/cdp/devtools/`
      );
    }
    if (typeof copy.devtoolsFrontendUrl === 'string') {
      // The frontend URL embeds `?ws=127.0.0.1:9222/devtools/...` as a query
      // param; rewrite that host:port too.
      copy.devtoolsFrontendUrl = copy.devtoolsFrontendUrl.replace(
        /127\.0\.0\.1:9222\/devtools\//g,
        `${host}/cdp/devtools/`
      );
    }
    return copy;
  });
}

function proxyChromiumJson(upstreamPath, req, res, transform) {
  if (!readSettings().remoteDebugEnabled) {
    return res.status(403).type('text/plain').send('Remote debugging disabled. Toggle "Allow remote debugging" in Advanced settings.');
  }
  const upstream = http.request({
    host: '127.0.0.1',
    port: 9222,
    path: upstreamPath,
    method: 'GET',
    // Chromium's CDP rejects non-localhost Host headers unless --remote-allow-origins
    // matches. Forcing Host: 127.0.0.1 dodges that entirely.
    headers: { Host: '127.0.0.1' },
  }, (upRes) => {
    let body = '';
    upRes.on('data', (c) => { body += c; });
    upRes.on('end', () => {
      try {
        let data = JSON.parse(body);
        if (transform) data = transform(data, req);
        res.type('application/json').send(JSON.stringify(data, null, 2));
      } catch (e) {
        res.status(502).type('text/plain').send('CDP proxy parse error: ' + e.message);
      }
    });
  });
  upstream.on('error', (e) => res.status(502).type('text/plain').send('Upstream error: ' + e.message));
  upstream.end();
}

function bridgeCdpWebSocket(reqUrl, clientWs) {
  const chromiumPath = reqUrl.replace(/^\/cdp/, '');
  let upstreamReady = false;
  const pending = [];
  const upstream = new WebSocket('ws://127.0.0.1:9222' + chromiumPath, {
    headers: { Host: '127.0.0.1' },
  });

  upstream.on('open', () => {
    upstreamReady = true;
    while (pending.length) {
      const m = pending.shift();
      try { upstream.send(m.data, { binary: m.isBinary }); } catch {}
    }
  });

  upstream.on('message', (data, isBinary) => {
    try { clientWs.send(data, { binary: isBinary }); } catch {}
  });

  clientWs.on('message', (data, isBinary) => {
    if (upstreamReady) {
      try { upstream.send(data, { binary: isBinary }); } catch {}
    } else {
      pending.push({ data, isBinary });
    }
  });

  const closeBoth = () => {
    try { if (clientWs.readyState <= WebSocket.OPEN) clientWs.close(); } catch {}
    try { if (upstream.readyState <= WebSocket.OPEN) upstream.close(); } catch {}
  };
  clientWs.on('close', closeBoth);
  upstream.on('close', closeBoth);
  clientWs.on('error', closeBoth);
  upstream.on('error', closeBoth);
}

app.get('/cdp/json/version', (req, res) => proxyChromiumJson('/json/version', req, res));
app.get(['/cdp/json', '/cdp/json/list'], (req, res) => proxyChromiumJson('/json', req, res, rewriteTabsList));

// ------------------------------------------------------------------------

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// --- REST API ---

app.get('/api/settings', (req, res) => {
  res.json(readSettings());
});

// Plain-text endpoints used by both the admin UI's Advanced modal and the
// kiosk autostart shell script. text/plain (not JSON) so bash can pipe the
// body directly into `xargs` / a flag array without JSON parsing.
// Kiosk launch target as bare "URL\nWIDTHxHEIGHT" — no JSON. chromium-autostart.sh
// used to sed the /api/settings JSON for "url", but bookmarks (added in c638a7d)
// introduced multiple "url":"..." keys, and the greedy sed matched the LAST one
// (a bookmark's URL) instead of the top-level url. Result: after clicking a
// bookmark then Restart kiosk, the kiosk came back on the wrong page. Serving
// the resolved values here removes all string-parsing ambiguity on the Pi.
app.get('/api/kiosk-target', (req, res) => {
  const s = readSettings();
  const w = s.resolution && s.resolution.width;
  const h = s.resolution && s.resolution.height;
  res.type('text/plain').send(`${s.url}\n${w}x${h}`);
});

app.get('/api/kiosk-flags', (req, res) => {
  res.type('text/plain').send(readSettings().kioskFlags);
});

app.get('/api/kiosk-flags/default', (req, res) => {
  res.type('text/plain').send(DEFAULT_KIOSK_FLAGS);
});

// labwc rc.xml for the current suppress-keys selection. chromium-autostart.sh
// writes this verbatim to $LABWC_HOME/labwc/rc.xml on every kiosk (re)start,
// the same propagation model as /api/kiosk-flags and the autostart file —
// no manual edits on the Pi, changes take effect on the next kiosk restart.
app.get('/api/labwc-config', (req, res) => {
  res.type('application/xml').send(buildLabwcConfig(readSettings().suppressKeys));
});

// The catalog of suppressible keys, so the Advanced UI can render a checkbox
// per key without hardcoding the list (server stays the single source of truth).
app.get('/api/suppress-keys', (req, res) => {
  res.json({
    available: Object.entries(SUPPRESSIBLE_KEYS).map(([id, v]) => ({ id, label: v.label })),
    enabled: readSettings().suppressKeys,
  });
});

app.post('/api/settings', (req, res) => {
  const current = readSettings();
  const updated = { ...current, ...req.body };
  if (req.body.resolution) {
    updated.resolution = { ...current.resolution, ...req.body.resolution };
  }
  writeSettings(updated);
  res.json(updated);
});

app.get('/api/system-info', async (req, res) => {
  try {
    const info = await getSystemInfo();
    info.git = update.getGitInfo(__dirname);
    res.json(info);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/status', async (req, res) => {
  let currentUrl = null;
  try {
    currentUrl = await cdp.getCurrentUrl();
  } catch {}
  res.json({
    browser_connected: cdp.isConnected(),
    current_url: currentUrl,
    settings: readSettings(),
  });
});

app.post('/api/navigate', async (req, res) => {
  const { url } = req.body;
  if (!url) return res.status(400).json({ error: 'url required' });
  try {
    const settings = readSettings();
    settings.url = url;
    writeSettings(settings);
    await cdp.navigate(url);
    res.json({ ok: true });
    broadcastStatus();
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/reload', async (req, res) => {
  try {
    // Always hard-reload so the kiosk picks up new JS/CSS/images after a deploy
    // without needing a cachebuster in the URL.
    await cdp.reload(true);
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/clear-cache', async (req, res) => {
  try {
    await cdp.clearBrowserCache();
    await cdp.reload(true);
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/zoom', async (req, res) => {
  const { zoom } = req.body;
  if (!zoom || zoom < 0.25 || zoom > 5) return res.status(400).json({ error: 'zoom must be 0.25-5' });
  try {
    const settings = readSettings();
    settings.zoom = zoom;
    writeSettings(settings);
    await cdp.setZoom(zoom);
    res.json({ ok: true });
    broadcastStatus();
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/click', async (req, res) => {
  const { x, y } = req.body;
  if (x == null || y == null) return res.status(400).json({ error: 'x and y required' });
  try {
    await cdp.click(Math.round(x), Math.round(y));
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Toggle between kiosk URL and the admin panel served at localhost. Bound to
// a USB-keyboard hotkey via lib/hotkey.js (evdev) so the user can pop into
// admin without network access — handy when WiFi/tunnel is flaky.
app.post('/api/admin-toggle', async (req, res) => {
  try {
    const result = await toggleAdminPanel();
    res.json({ ok: true, ...result });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/restart-kiosk', async (req, res) => {
  try {
    if (process.env.ORBIT_DEV === '1') {
      await cdp.closeBrowser();
    } else {
      await restartKiosk();
    }
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/reboot', (req, res) => {
  res.json({ ok: true, message: 'Rebooting...' });
  setTimeout(() => reboot(), 1000);
});

// --- WiFi management ---

app.get('/api/wifi/status', async (req, res) => {
  try {
    const [status, saved] = await Promise.all([wifi.getStatus(), wifi.listSaved()]);
    res.json({ status, saved });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/wifi/scan', async (req, res) => {
  try {
    res.json({ networks: await wifi.scan() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/wifi/connect', async (req, res) => {
  const { ssid, password } = req.body || {};
  if (!ssid) return res.status(400).json({ error: 'ssid required' });
  try {
    const result = await wifi.connect(ssid, password);
    res.json({ ok: true, ...result });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/wifi/forget', async (req, res) => {
  const { ssid } = req.body || {};
  if (!ssid) return res.status(400).json({ error: 'ssid required' });
  try {
    res.json(await wifi.forget(ssid));
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

let updateInProgress = false;

app.post('/api/update', async (req, res) => {
  if (updateInProgress) return res.status(409).json({ error: 'update already running' });
  if (process.env.ORBIT_DEV === '1') {
    return res.status(400).json({ error: 'update is disabled in dev mode' });
  }
  updateInProgress = true;
  res.json({ ok: true });

  const broadcast = (msg) => {
    const data = JSON.stringify(msg);
    for (const ws of controlClients) {
      if (ws.readyState === 1) ws.send(data);
    }
  };

  try {
    await update.runUpdate(__dirname, {
      onLine: (stream, line) => broadcast({ type: 'update-output', stream, line }),
      onStep: (step) => broadcast({ type: 'update-step', step }),
    });
    update.invalidateGitInfoCache();
    broadcast({ type: 'update-status', status: 'restarting' });
    // Restart via systemd rather than process.exit(0). Under load (10 hotkey
    // fs.createReadStreams blocking the libuv thread pool + high-fps preview
    // broadcasts) Node's own exit has been observed to stall mid-V8-shutdown,
    // leaving the service "active" but stuck. `systemctl restart` is an
    // out-of-band SIGTERM from PID 1 — kernel terminates blocked threads
    // and systemd guarantees the new instance comes up.
    setTimeout(() => {
      spawn('systemctl', ['restart', 'orbit-control'], {
        detached: true,
        stdio: 'ignore',
      }).unref();
    }, 1000);
  } catch (err) {
    broadcast({ type: 'update-status', status: 'error', error: err.message });
    updateInProgress = false;
  }
});

// --- WebSocket (control panel live updates + preview) ---

const controlClients = new Set();

function broadcastStatus() {
  const data = JSON.stringify({
    type: 'status',
    browser_connected: cdp.isConnected(),
    settings: readSettings(),
  });
  for (const ws of controlClients) {
    if (ws.readyState === 1) ws.send(data);
  }
}

function updatePreview() {
  // Preview FPS is a per-client preference (stored in the client's localStorage)
  // because it's about *how fast the operator wants to watch* the kiosk, not
  // anything about the kiosk itself. With multiple panels open we use the
  // max requested rate so a slow client doesn't throttle a fast one — the
  // slow one just receives more frames than it strictly needs.
  let maxFps = 1;
  let wsWant = false;
  for (const ws of controlClients) {
    if (!ws._wantPreview) continue;
    wsWant = true;
    const fps = ws._previewFps || 1;
    if (fps > maxFps) maxFps = fps;
  }
  const anyWant = wsWant || mjpegClients.size > 0;
  if (anyWant && cdp.isConnected()) {
    cdp.setPreviewFps(maxFps);
    cdp.startPreview();
  } else {
    cdp.stopPreview();
  }
}

wss.on('connection', (ws) => {
  controlClients.add(ws);
  ws._wantPreview = false;
  ws._previewFps = 1;

  ws.send(JSON.stringify({
    type: 'status',
    browser_connected: cdp.isConnected(),
    settings: readSettings(),
  }));
  // Fire a system-info/wifi push to this WS immediately so it doesn't have to
  // wait up to STATUS_PUSH_INTERVAL_MS for the next periodic broadcast.
  pushStatusUpdates();

  ws.on('message', (raw) => {
    let msg;
    try { msg = JSON.parse(raw); } catch { return; }

    if (msg.type === 'preview-start') {
      ws._wantPreview = true;
      if (msg.fps) ws._previewFps = Math.max(1, Math.min(30, parseInt(msg.fps, 10) || 1));
      updatePreview();
    } else if (msg.type === 'preview-stop') {
      ws._wantPreview = false;
      updatePreview();
    } else if (msg.type === 'preview-fps') {
      ws._previewFps = Math.max(1, Math.min(30, parseInt(msg.fps, 10) || 1));
      updatePreview();
    } else if (msg.type === 'mouse') {
      // Forward raw pointer events from the preview pane to chromium via CDP.
      // Coords arrive as normalized 0..1 (the preview video can be at any
      // resolution); scale here by the kiosk's actual viewport size so CDP
      // gets coordinates in the page's CSS pixel space. Wheel deltas pass
      // through as-is since they're already in CSS pixels.
      const { action } = msg;
      if (typeof msg.x !== 'number' || typeof msg.y !== 'number') return;
      const res = readSettings().resolution || { width: 1920, height: 1080 };
      const x = Math.max(0, Math.min(res.width,  msg.x * res.width));
      const y = Math.max(0, Math.min(res.height, msg.y * res.height));
      cdp.mouseEvent(action, x, y, {
        button: msg.button,
        buttons: msg.buttons,
        dx: msg.dx,
        dy: msg.dy,
        clickCount: msg.clickCount,
      }).catch(() => {});
    }
  });

  ws.on('close', () => {
    controlClients.delete(ws);
    updatePreview();
  });
});

// --- MJPEG preview stream over HTTP ---
// Each connected admin panel opens a long-lived `GET /preview.mjpeg` request.
// chromium's screencast JPEGs are written to all open responses as multipart
// frames (the same protocol IP cameras use). The browser handles decode +
// repaint natively via <img>, so there's zero JS per frame and no encoding
// step on the Pi — just byte-pipe from chromium → HTTP clients.
const MJPEG_BOUNDARY = 'orbit-frame';
const mjpegClients = new Set();

cdp.setOnScreenshotFrame((jpegBuf) => {
  if (mjpegClients.size === 0) return;
  const header = Buffer.from(
    `\r\n--${MJPEG_BOUNDARY}\r\nContent-Type: image/jpeg\r\nContent-Length: ${jpegBuf.length}\r\n\r\n`,
    'ascii'
  );
  for (const res of mjpegClients) {
    try {
      res.write(header);
      res.write(jpegBuf);
    } catch {}
  }
});

app.get('/preview.mjpeg', (req, res) => {
  res.writeHead(200, {
    'Content-Type': `multipart/x-mixed-replace; boundary=${MJPEG_BOUNDARY}`,
    'Cache-Control': 'no-cache, no-store, max-age=0',
    'Pragma': 'no-cache',
    'Connection': 'close',
    'X-Accel-Buffering': 'no', // disable proxy buffering (cloudflared, nginx)
  });
  mjpegClients.add(res);
  // Trigger screencast if not already running so frames start flowing
  // immediately, without waiting for the panel's WS preview-start.
  updatePreview();
  req.on('close', () => {
    mjpegClients.delete(res);
    updatePreview();
  });
  req.on('error', () => {
    mjpegClients.delete(res);
    updatePreview();
  });
});

// --- CDP connection state ---
cdp.setOnConnectChange(async (connected) => {
  broadcastStatus();
  if (connected) {
    updatePreview();
    const settings = readSettings();
    if (settings.zoom && settings.zoom !== 1) {
      cdp.setZoom(settings.zoom).catch(() => {});
    }
    // Navigate to saved URL if browser is on a blank page
    try {
      const currentUrl = await cdp.getCurrentUrl();
      if (settings.url && (!currentUrl || currentUrl === 'about:blank' || currentUrl === 'chrome://newtab/')) {
        cdp.navigate(settings.url).catch(() => {});
      }
    } catch {}
  }
});

// --- Start ---

const PORT = parseInt(process.env.PORT, 10) || 80;
// Push system-info + wifi-status to all connected control clients every few
// seconds. Replaces the previous per-client HTTP polling — same data, one
// gather, broadcast over the existing WS so there's no duplicate work and
// no roundtrip storm.
const STATUS_PUSH_INTERVAL_MS = 5000;
function broadcastJson(obj) {
  const data = JSON.stringify(obj);
  for (const ws of controlClients) {
    if (ws.readyState === 1) {
      try { ws.send(data); } catch {}
    }
  }
}

async function pushStatusUpdates() {
  if (controlClients.size === 0) return;
  try {
    const info = await getSystemInfo();
    info.git = update.getGitInfo(__dirname);
    broadcastJson({ type: 'system-info', info });
  } catch {}
  try {
    const [status, saved] = await Promise.all([wifi.getStatus(), wifi.listSaved()]);
    broadcastJson({ type: 'wifi-status', status, saved });
  } catch {}
}
setInterval(pushStatusUpdates, STATUS_PUSH_INTERVAL_MS);

server.listen(PORT, () => {
  console.log(`OrbitControl running on http://0.0.0.0:${PORT}`);
  cdp.connect();
  hotkey.start(() => {
    toggleAdminPanel().catch((err) =>
      console.warn('[hotkey] toggle failed:', err.message)
    );
  });
});
